#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai_config=(
	# Layout
	external_bar all:40:0
	layout float
	bottom_padding 10
	left_padding 10
	right_padding 10
	window_gap 10

	# Mouse
	mouse_follows_focus on
	focus_follows_mouse on
	mouse_modifier               alt
	mouse_action1                move
	mouse_action2                resize

	# window
	window_placement second_child
	window_opacity off
	window_opacity_duration 0.0
	window_shadow on
	window_animation_duration 0.2
	active_window_opacity 1.0
	normal_window_opacity 0.90
	split_ratio 0.50
)

yabai -m config "${yabai_config[@]}"

yabai -m config layout bsp

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Stickies|Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

JB_Apps='^(WebStorm|PyCharm.*|IntelliJ.*|GoLand)$'
yabai -m rule --add app="${JB_Apps}" title!=".*\[.*\].*"  manage=off
echo "yabai configuration loaded.."

