#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai_config=(
	# Layout
	external_bar all:40:0
	layout float
	bottom_padding 10
	left_padding 10
	right_padding 10
	window_gap 10

	# Mouse
	mouse_modifier               alt
	mouse_action1                move
	mouse_action2                resize

	# window
	window_placement second_child
	window_opacity off
	window_opacity_duration 0.0
	window_shadow on
	window_animation_duration 0.2
	window_animation_easing easeOutCirc
	active_window_opacity 1.0
	normal_window_opacity 0.90
	split_ratio 0.50
)

yabai -m config "${yabai_config[@]}"

yabai -m config layout bsp

#Custom event for sketchybar
yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Harvest|Stickies|Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m rule --add label="Arc video" app="Arc" title="" manage=off

JB_Apps='^(WebStorm|PyCharm|IntelliJ.*|GoLand)$'
JB_TITLE='(Run\/Debug.*|Settings|Rename|Conflicts|Copy|Merge Revisions.*|Delete|Move|Keyboard Shortcut|Notifications|Data Sources and Drivers|Database|Database Query|Database Search|Change Signature.*|File Cache Conflict|Extract .*)'
yabai -m rule --add app="${JB_Apps}" title="${JB_TITLE}" manage=off

echo "yabai configuration loaded.."

