return function(icon)
	local icons = {
		["Terminal"] = "",
		["Alacritty"] = "",
		["Antidote 11"] = "",
		["Google Chrome"] = "",
		["Arc"] = "",
		["Safari"] = "",
		["Bitwarden"] = "",
		["Cursor"] = "",
		["Calendar"] = "󰃭",
		["Todoist"] = "󰃭",
		["Discord"] = "󰙯",
		["Docker Desktop"] = "󰡨",
		["Figma"] = "",
		["Harvest"] = "",
		["WebStorm"] = "󰛦",
		["IntelliJ IDEA"] = "",
		["PyCharm"] = "",
		["Keynote"] = "󰐨",
		["Microsoft PowerPoint"] = "󰐨",
		["Mail"] = "󰇮",
		["Outlook"] = "󰇮",
		["Numbers"] = "󱎏",
		["Microsoft Excel"] = "󱎏",
		["Pages"] = "",
		["Microsoft Word"] = "",
		["Microsoft Teams (work or school)"] = "󰊻",
		["Microsoft Teams classic"] = "󰊻",
		["MongoDB Compass"] = "",
		["Music"] = "",
		["Spotify"] = "",
		["Notion"] = "󱞎",
		["Obsidian"] = "󱞎",
		["Notes"] = "󱞎",
		["Stickies"] = "󱞎",
		["Postman"] = "󱂛",
		["Bruno"] = "󱂛",
		["Preview"] = "",
		["Photo"] = "",
		["Slack"] = "",
		["System Settings"] = "󰒓",
		["Code"] = "",
		["Finder"] = "󰉋",
		["DataGrip"] = "󱤟",
        ["Claude"] = "󱜙",
	}

	return icons[icon] or ""
end
